services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: rad-gallery-frontend
    restart: unless-stopped

    expose:
      - "5173"

    networks:
      - web

networks:
  web:
    external: true