version: "3.8"

services:
  frontend:
    build: .

    restart: always

    env_file:
      - .env.production

    expose:
      - "5173"

    command: ["serve", "-s", "dist", "-l", "5173"]

    networks:
      - web

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.rad-gallery-frontend.rule=Host(`rad-gallery-isf.ir`) || Host(`www.rad-gallery-isf.ir`)"
      - "traefik.http.routers.rad-gallery-frontend.entrypoints=websecure"
      - "traefik.http.routers.rad-gallery-frontend.tls=true"
      - "traefik.http.services.rad-gallery-frontend.loadbalancer.server.port=5173"

networks:
  web:
    external: true